### ISSUE TITLE
Issue From tutoring 

### ISSUE THREAD

**Issue by madelyng8** [madelyng8/responsive-icon-cards#1]
Hi @MackenzieRose currently in my screen shots 2 are correct and three are incorrect, I am confused with next steps and the parse error which I cannot seem to solve. Thanks!

**Comment by MacKenzieRose** [comment]
If this issue has been resolved, feel free to close it :)

Cheers!
MacKenzie

**Comment by MacKenzieRose** [comment]
If this issue has been addressed, please make sure to close it 😄

**Comment by madelyng8** [comment]
Hi Mackenzie,

I just closed all the issues. Sorry about that. Let me know if I need to
resolve something else?

Thanks so much for your help,

Matti G-S
